/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#4edea3",
        "outline-variant": "#4a4455",
        "on-background": "#e5e2e3",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-fixed-variant": "#5a00c6",
        "on-primary": "#3f008e",
        "inverse-on-surface": "#313031",
        "secondary-container": "#4b4b52",
        "on-secondary-container": "#bcbbc3",
        "on-secondary": "#303037",
        "surface": "#131314",
        "inverse-surface": "#e5e2e3",
        "on-surface": "#e5e2e3",
        "secondary-fixed-dim": "#c7c5ce",
        "primary": "#d2bbff",
        "on-primary-container": "#ede0ff",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-container": "#76ffc2",
        "surface-variant": "#353436",
        "surface-container": "#201f20",
        "surface-bright": "#3a393a",
        "outline": "#958da1",
        "on-secondary-fixed": "#1b1b21",
        "on-error": "#690005",
        "on-tertiary-fixed": "#002113",
        "surface-dim": "#131314",
        "surface-container-low": "#1c1b1c",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "secondary": "#c7c5ce",
        "primary-fixed": "#eaddff",
        "on-primary-fixed": "#25005a",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0e0e0f",
        "surface-container-high": "#2a2a2b",
        "secondary-fixed": "#e3e1ea",
        "background": "#131314",
        "primary-container": "#7c3aed",
        "surface-tint": "#d2bbff",
        "surface-container-highest": "#353436",
        "on-secondary-fixed-variant": "#46464d",
        "on-surface-variant": "#ccc3d8",
        "tertiary-container": "#007650",
        "tertiary": "#4edea3",
        "on-tertiary": "#003824",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-primary": "#732ee4"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"],
        "mono": ["JetBrains Mono"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
